# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='descricao')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:')),
                ('status', models.CharField(choices=[(b'd', b'Despublicado'), (b'p', b'Publicado')], max_length=1)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Partner', verbose_name='Nome do Parceiro')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='descricao')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:')),
                ('status', models.CharField(choices=[(b'd', b'Despublicado'), (b'p', b'Publicado')], max_length=1)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Livro')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Partner')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
