# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='descricao')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:')),
                ('status', models.CharField(choices=[(b'd', b'Despublicado'), (b'p', b'Publicado')], max_length=1)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='descricao')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:')),
                ('status', models.CharField(choices=[(b'd', b'Despublicado'), (b'p', b'Publicado')], max_length=1)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Livro')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Partner')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
