# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
