# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Nome'),
        ),
    ]
