# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170314_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='sale',
            name='rules',
            field=models.TextField(blank=True, max_length=100, verbose_name='Regras de uso'),
        ),
        migrations.AddField(
            model_name='sale',
            name='validity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Validade'),
        ),
    ]
