# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('book', '0002_auto_20170309_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Crie uma senha'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cnpj',
            field=models.BigIntegerField(verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
