# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170304_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Imagem:'),
        ),
    ]
