# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170304_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
