# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170321_2039'),
        ('book', '0004_auto_20170322_0043'),
    ]

    operations = [
    ]
