# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_merge_20170322_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem 2:'),
        ),
        migrations.AddField(
            model_name='sale',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='Imagem 3:'),
        ),
    ]
