# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170322_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='rules',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Regras de uso'),
        ),
    ]
