# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('tipo_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo_pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='forma_pagamento')),
                ('state', models.CharField(choices=[('1', 'Autorizado'), ('2', 'Iniciado'), ('3', 'Boleto Impresso'), ('4', 'Concluido'), ('5', 'Cancelado'), ('6', 'Em analise'), ('7', 'Estornado'), ('9', 'Reembolsado')], max_length=200, verbose_name='status')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='value')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('id_moip', models.CharField(blank=True, max_length=200, null=True, verbose_name='id_moip')),
                ('date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User_Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('0', 'Utilizado'), ('1', 'Disponivel')], max_length=1, verbose_name='status')),
                ('user', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('id_user_sale', models.CharField(blank=True, max_length=501, null=True, verbose_name='ID_OFERTA_USUARIO')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moip.Purchase')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Sale')),
            ],
        ),
    ]
