# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0005_partner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='titulo')),
                ('state', models.CharField(max_length=200, verbose_name='status')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User')),
            ],
        ),
    ]
