# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sales',
            name='id_user_sale',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID_OFERTA_USUARIO'),
        ),
    ]
