# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='forma_pagamento',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='forma_pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='tipo_pagamento',
            field=models.CharField(default='CartaoDeCredito', max_length=100, verbose_name='tipo_pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='value',
            field=models.CharField(default=0, max_length=200, verbose_name='value'),
            preserve_default=False,
        ),
    ]
