# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('moip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200, verbose_name='status')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moip.Purchase')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Person')),
            ],
        ),
    ]
