# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moip', '0002_auto_20170314_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compra'},
        ),
        migrations.AlterModelOptions(
            name='user_sales',
            options={'verbose_name': 'Ofertas por Usuario', 'verbose_name_plural': 'Ofertas por Usuario'},
        ),
    ]
