# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moip', '0002_auto_20170309_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='id_moip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id_moip'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='forma_pagamento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo_pagamento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Person'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='value'),
        ),
    ]
