# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170309_0123'),
        ('moip', '0003_auto_20170309_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
