# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moip', '0006_auto_20170310_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sales',
            name='state',
            field=models.CharField(choices=[('1', 'Autorizado'), ('2', 'Iniciado'), ('3', 'Boleto Impresso'), ('4', 'Concluido'), ('5', 'Cancelado'), ('6', 'Em analise'), ('7', 'Estornado'), ('9', 'Reembolsado')], max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user_sales',
            name='user',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
